on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    permissions: write-all
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64-musl
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-armv7-musleabihf
            runs-on: ubuntu-24.04
            target: armv7-unknown-linux-musleabihf

          - os-name: Linux-armv6-musleabihf
            runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabihf

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin

          - os-name: macOS-arm64
            runs-on: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: force static CRT for musl targets (may break some crates).
      # - name: Set RUSTFLAGS for musl static linking
      #   if: contains(matrix.platform.target, 'musl')
      #   run: echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.platform.target }}/release/treegen-rs${{ matrix.platform.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
          asset_name: treegen-rs-${{ matrix.platform.os-name }}${{ matrix.platform.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
          asset_content_type: application/octet-stream
